server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.56.101:3306/Spring?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root1
    password: root